apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-localai
  namespace: k8sgpt
spec:
  ai:
    enabled: true
    backend: localai
    # Use the same model name as the one used into the LocalAI helm chart's values.yaml
    #model: ggml-gpt4all-j.bin
    model: gpt-4
    # kubernetes-internal DNS name of the local-ai Service
    #baseUrl: http://local-ai.local-ai.svc.cluster.local:8080/v1
    baseUrl: http://local-ai.local-ai.svc.cluster.local/v1

    # secret:
    #  name: k8sgpt-sample-secret
    #  key: openai-api-key
    # anonymized: false
    # language: english

    # Allow K8sGPT to store AI analyses in an in-memory cache, otherwise the cluster may get throttled
  noCache: false
  version: v0.3.29